name: 'Lint, Prettify, and Test'

description: 'Run ESLint, Prettier, and Jest'

runs:
  runs-on: ubuntu-latest
  steps:
    - name: Run ESLint
    run: yarn lint
    shell: bash

  - name: Run Prettier
    run: yarn prettier:check
    shell: bash

  - name: Run tests
    run: yarn test
    shell: bash
