name: CD Bookstore

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    uses: './.github/workflows/ci.yml'

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy
        run: echo "Deploying... (Coming in later sessions)"
        shell: bash
