name: CI Bookstore

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js and Install Dependencies
        uses: ./setup-node-and-install
        with:
          node-version: '20'

      - name: Run ESLint
        run: npm run lint
        shell: bash

      - name: Run Prettier
        run: npm run prettier:check
        shell: bash

      - name: Run tests
        run: npm run test
        shell: bash
